[tool.black]
line-length = 120
target-version = ['py310']
include = '''
((yukon|tests)/.*\.pyi?$)
'''
[tool.pytest.ini_options]
log_cli = true
log_cli_level = "NOTSET"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_file = "pytest.log"