name: Deploy artifacts to GitHub Releases

#
# A reuseable workflow to deploy an artifact to GitHub Releases
#

on:
  workflow_call:

jobs:
  push-to-gh-releases:
    name: GitHub Releases
    runs-on: ubuntu-latest
    steps:
      # Download the artifacts
      - name: Download artifact
        uses: actions/download-artifact@v3

    #
    # - name: Deploy the release to GitHub Releases
    #   uses: fnkr/github-action-ghr@v1
    #   if: startsWith(github.ref, 'refs/tags/2[0-9][0-9][0-9].[0-9]?[0-9].[0-9]+')
    #   env:
    #     GHR_PATH: dist/Yukon/
    #     GITHUB_TOKEN: ${{ secrets.OPENCYPHAL_TOKEN }}

