name: Deploy artifacts to GitHub Releases

#
# A reuseable workflow to deploy an artifact to GitHub Releases
#

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  push-to-gh-releases:
    name: GitHub Releases
    runs-on: ubuntu-latest
    steps:
      # Download the artifacts
      - name: Download artifact
        uses: actions/download-artifact@v3

      # Tag commit with version number
      - name: Push version tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.OPENCYPHAL_TOKEN }}
          custom_tag: ${{ inputs.version }}
          tag_prefix: ''

    #
    # - name: Deploy the release to GitHub Releases
    #   uses: fnkr/github-action-ghr@v1
    #   if: startsWith(github.ref, 'refs/tags/2[0-9][0-9][0-9].[0-9]?[0-9].[0-9]+')
    #   env:
    #     GHR_PATH: dist/Yukon/
    #     GITHUB_TOKEN: ${{ secrets.OPENCYPHAL_TOKEN }}

