name: 'Yukon application builder'

# Builds Yukon OpenCyphal IDE artifacts

on:
  push:
    branches:
#      - main
      - issue-200

# This ensures that only one workflow is running
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  #
  # Ubuntu 20.04 build
  #
  ubuntu-focal:
    name: Build Yukon Ubuntu 20.04
    runs-on: ubuntu-20.04
    outputs:
      yukon-version: ${{ steps.build-release.outputs.version }}
      artifact-name: ${{ steps.set-name.outputs.artifact-name }}
    steps:
      - name: Checking out
        uses: actions/checkout@v3

      - name: Installing Python3
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Setting up Node.js
        uses: actions/setup-node@v3

      - name: Installing dependencies
        run: |
          sudo apt install libgfortran5 libquadmath0
          pip install yakut
          yakut compile -O.compiled $master_path
          python3.10 -m venv venv
          source venv/bin/activate
          pip install nox
          pip install -r requirements.txt -r dev-requirements.txt
        env:
          master_path: https://github.com/OpenCyphal/public_regulated_data_types/archive/refs/heads/master.zip

      - id: build-release
        name: Building release
        continue-on-error: false
        run: |
          source venv/bin/activate
          python3.10 build_exe.py
          echo "version=$(python3 -c 'from yukon.version import __version__; print(__version__)')" >> $GITHUB_OUTPUT

      - name: Saving artifact
        uses: actions/upload-artifact@v3
        with:
          name: Yukon-${{ github.job }}
          path: dist/Yukon
          retention-days: 1

      - id: set-name
        name: Storing artifact name
        run: |
          echo "artifact-name=Yukon-${{ github.job }}" >> $GITHUB_OUTPUT

  #
  # Deploy artifacts to files.zubax.com
  #
  deploy-to-zubax:
    name: Deploy
    needs: ubuntu-focal
    uses: ./.github/workflows/deploy-to-zubax.yml
    with:
      product: org.opencyphal.yukon
      version: ${{ needs.ubuntu-focal.outputs.yukon-version }}
      architecture: linux-x86_64
      artifact-name: ${{ needs.ubuntu-focal.outputs.artifact-name }}
    secrets: inherit
