name: Yukon tests
on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'   # excludes master
jobs:
  python-quality-check:
    runs-on: ubuntu-22.04
    steps:
      - name: checking out
        uses: actions/checkout@v2
      - name: Installing Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: installing dependencies
        run: |
          pip install yakut
          yakut compile -O.compiled https://github.com/OpenCyphal/public_regulated_data_types/archive/refs/heads/master.zip
          pip install nox
          pip install -r requirements.txt -r dev-requirements.txt
      - name: Testing GUI
        run: |
          PYTHONPATH=".:.." nox -s mypy
          PYTHONPATH=".:.." nox -s black
          PYTHONPATH=".:.." nox -s pylint
  immediate-release-linux:
    runs-on: ubuntu-20.04
    if:
      contains(github.event.head_commit.message, '#release-linux')
    steps:
      - name: checking out
        uses: actions/checkout@v2
      - name: Installing Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - uses: actions/setup-node@v3
      - name: installing dependencies
        run: |
          pip install yakut
          yakut compile -O.compiled https://github.com/OpenCyphal/public_regulated_data_types/archive/refs/heads/master.zip
          pip install nox
          pip install -r requirements.txt -r dev-requirements.txt
      - name: Testing GUI
        run: |
          PYTHONPATH=".:.." nox -s mypy
          PYTHONPATH=".:.." nox -s black
          PYTHONPATH=".:.." nox -s pylint
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          cat >>~/.ssh/config <<END
          Host target
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/private.key
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: Build the release using the script, which will call pyinstaller
        continue-on-error: false
        run: |
          python3.10 build_exe.py
      - name: Deploy the release
        if: ${{ success() }}
        run: |
          YUKON_VERSION_1=$(python3 -c "from yukon.version import __version__; print(__version__)")
          YUKON_VERSION=$(python3 -c "from yukon.version import __version__; print(__version__)")
          YUKON_TARGET_DIR=/var/www/files/products/org.opencyphal.yukon/releases/$YUKON_VERSION/linux-x86_64
          ssh target "mkdir -p $YUKON_TARGET_DIR; echo $YUKON_TARGET_DIR"
          scp $YUKON_ARTIFACT target:$YUKON_TARGET_DIR
        env:
          YUKON_ARTIFACT: dist/Yukon
  immediate-release-windows:
    name: Yukon Windows Build
    runs-on: windows-latest
    if:
      contains(github.event.head_commit.message, '#release-windows')
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3
      - name: Installing Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - uses: actions/setup-node@v3
      - name: Installing dependencies
        run: |
          pip install wheel yakut
          yakut compile -O.compiled https://github.com/OpenCyphal/public_regulated_data_types/archive/refs/heads/master.zip
          pip install nox
          python3 --version
          pip install -r requirements.txt -r dev-requirements.txt
      - name: Testing GUI
        run: |
          $Env:PYTHONPATH = ".:.."
          nox -s mypy
          nox -s black
          nox -s pylint
      - name: Building release
        run: python3 build_exe.py
      - name: Configure OpenSSH parameters
        if: ${{ success() }}
        uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
        with:
          ORIGIN: ${{ secrets.SSH_HOST }}
          SSHKEY: ${{ secrets.SSH_KEY }}
          NAME: target
          USER: ${{ secrets.SSH_USERNAME }}
      - name: Copy artifact to remote file server
        run: |
          Add-Content -Path "C:\Users\runneradmin\.ssh\access" -Value "`n" -NoNewLine  # Hack: add newline to end of key on Windows Server 2022
          $YUKON_VERSION = (python3 -c "from yukon.version import __version__; print(__version__)")
          $YUKON_TARGET_DIR = "/var/www/files/products/org.opencyphal.yukon/releases/${YUKON_VERSION}/windows-x86_64"
          ssh target "mkdir -p $YUKON_TARGET_DIR; echo $YUKON_TARGET_DIR"
          scp $Env:YUKON_ARTIFACT target:${YUKON_TARGET_DIR}
        env:
          YUKON_ARTIFACT: ./dist/Yukon.exe