name: KucherX tests
on: push
jobs:
  runtests:
    runs-on: ubuntu-22.04
    env:
      DISPLAY: :1
    steps:
      - name: checking out
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: installing dependencies
        run: |
          git submodule update --init
          pip install yakut
          yakut compile -O.compiled https://github.com/OpenCyphal/public_regulated_data_types/archive/refs/heads/master.zip
          pip install nox
          python3.10 -m pip install -r requirements.txt
          python3.10 setup.py build_py
      - name: Testing GUI
        run: |
          PYTHONPATH=".:.." nox -s mypy
          PYTHONPATH=".:.." nox -s black
          PYTHONPATH=".:.." nox -s pylint
